apiVersion: extensions/v1beta1
kind: Daemonset
metadata:
  name: weavescope-test-plugin
  labels:
    app: weavescope
    weavescope-component: weavescope-test-plugin
spec:
  template:
    metadata:
      labels:
        app: weavescope
        weavescope-component: weavescope-test-plugin
    spec:
      hostPID: true
      hostNetwork: true
      containers:
        - name: weavescope-test-plugin
          image: mycluster.icp:8500/weave/scope-test:latest
          securityContext:
            privileged: true
          volumeMounts:
            - name: scope-plugins
              mountPath: /var/run/scope/plugins
      imagePullSecrets:
        - name: regsecret
      volumes:
        - name: scope-plugins
          hostPath:
            path: /var/run/scope/plugins
