apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  labels:
    app: weavescope
    weavescope-component: weavescope-icp-dashboard-plugin
  name: weavescope-icp-dashboard-plugin
spec:
  template:
    metadata:
      labels:
        app: weavescope
        weavescope-component: weavescope-icp-dashboard-plugin
    spec:
      hostPID: true
      hostNetwork: true
      containers:
        - name: weavescope-icp-dashboard-plugin
          image: sidneywibm/weavescope-icp-dashboard-plugin:latest
          imagePullPolicy: Always
          securityContext:
            privileged: true
          volumeMounts:
          - name: scope-plugins
            mountPath: /var/run/scope/plugins
          env:
            - name: ICP_DASHBOARD
              valueFrom:
                configMapKeyRef:
                  name: icp-dashboard
                  key: dashboard-link

      volumes:
      - name: scope-plugins
        hostPath:
          path: /var/run/scope/plugins
      imagePullSecrets:
        - name: regsecret
